apiVersion: apps/v1
kind: Deployment
<<<<<<< HEAD

metadata:
  name: auth-depl

=======
metadata:
  name: auth-depl
>>>>>>> e770231b1242ba419e9039f0b05d631147ce6e00
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
<<<<<<< HEAD
          image: john/auth
=======
          image: yonasenchalew1993/auth
>>>>>>> e770231b1242ba419e9039f0b05d631147ce6e00
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
<<<<<<< HEAD
  namespace: default
=======
>>>>>>> e770231b1242ba419e9039f0b05d631147ce6e00
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
<<<<<<< HEAD
      targetPort: 3000
---

=======
      targetPort: 3000
>>>>>>> e770231b1242ba419e9039f0b05d631147ce6e00
